default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cloud_storage_development

test:
  <<: *default
  database: cloud_storage_test
#     url: <%= ENV['DATABASE_URL'] %>

production:
  <<: *default
  database: cloud_storage_production
  username: cloud_storage
  password: <%= ENV['CLOUD_STORAGE_DATABASE_PASSWORD'] %>
